<div class="card zh">
    <blockquote>
        <p>
            尊敬的用户，您好：
        </p>
        <blockquote>
            <p>
                本邮件内容为codepasser.com发送给您的密码重置验证码。
            </p>
            <p>
                请复制下面的验证码(10分钟内有效)，完成密码重置流程：
            </p>
            <p>
                验证码：${token}
            </p>
            <p>
                以防不是您本人在codepasser.com进行操作，请忽略此消息。
            </p>
            <p>
                如果您有任何问题，请联系我们:&nbsp;admin@codepasser.com
            </p>
        </blockquote>
        <p>
            codepasser.com
        </p>
    </blockquote>
</div>
