# Server configuration
server:
  port: ${cloud.configuration.port:8888}

# Log configuration
logging:
  level:
    org.springframework.cloud: DEBUG

# Actuator health configuration
management:
  endpoint:
    health:
      show-details: always
