# Server configuration
server:
  port: ${service.base.port:9001}
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

# Eureka configuration
eureka:
  client:
    # 指定服务注册中心地址，类型为 HashMap，并设置有一组默认值，默认的Key为 defaultZone；默认的Value为 http://localhost:8761/eureka ，如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
    # 如果服务注册中心加入了安全验证，这里配置的地址格式为： http://<username>:<password>@localhost:8761/eureka 其中 <username> 为安全校验的用户名；<password> 为该用户的密码
    service-url:
      defaultZone: ${cloud.registry.uri:http://eureka:eureka_pw@127.0.0.1:8761/eureka}
  instance:
    # 设置当前实例的主机名称
    hostname: ${spring.cloud.client.hostname}
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}:${service.base.version:1.0.0.RELEASE}:${random.value}
    # 定义服务续约任务（心跳）的调用间隔，单位：秒 默认: 30s
    lease-renewal-interval-in-seconds: 3
    # 设置状态页面路径
    status-page-url-path: ${server.servlet.context-path}actuator/info
    # 设置信息页面路径
    health-check-url-path: ${server.servlet.context-path}actuator/health

# Spring configuration
spring:
  # Jackson
  jackson:
    # 配置mapper忽略空属性
    serialization-inclusion: non_null
    # 属性命名转化策略:将驼峰转为下划线
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  # Database
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.121:3306/daemon?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: daemon
    password: cde3VFR$
    # Datasource pool
    druid:
      # 监控统计拦截的filters
      filters: stat
      # 配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # MERGE SQL SLOW SQL
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # Jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
  # Redis
  redis:
    # > redis single
    # host: 172.16.20.121
    # port: 6379
    # database: 0
    password: cde3VFR$
    timeout: 10000
    # > redis cluster
    cluster:
      # 获取失败 最大重定向次数
      max-redirects: 3
      nodes:
        - 172.16.20.121:6379
        - 172.16.20.121:6380
        - 172.16.20.121:6381
        - 172.16.20.121:6389
        - 172.16.20.121:6390
        - 172.16.20.121:6391
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
  # Spring Data
  data:
    # Spring Data Mongo
    mongodb:
      host: 172.16.20.121
      port: 27017
      database: daemon
      username: daemon
      password: cde3VFR$
    # Spring Data ElasticSearch
    elasticsearch:
      clusterName: codepasser-cluster
      clusterNodes: 172.16.20.121:9301,172.16.20.121:9302,172.16.20.121:9303
      properties:
        transport:
          tcp:
            connect_timeout: 30s
  # Mail
  mail:
    host: smtp.codepasser.com
    port: 465
    nick-name: codepasser.com
    username: todo@codepasser.com
    password: todo
    properties:
      mail.smtp.auth: true
      mail.debug: false
      mail.smtp.timeout: 30000
      mail.smtp.port: 465
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
# Spring Data ElasticSearch 关闭ES健康检查
management:
  health:
    elasticsearch:
      enabled: false

# Mybatis
mybatis:
  #  type-handlers-package: org.codepasser.base.dao.repository.mapper.handlers
  type-aliases-package: org.codepasser.base.model.entity.dto
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

# Mybatis page helper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

daemon:
  base-url: http://www.codepasser.com
  service:
    identifying-code-timeout: 10 #  TimeUnit.MINUTES
    area-scope: '000000' # 全国
  mail:
    nick-name: codepasser.com
    username: todo@codepasser.com
    password: todo
    retry-count: 3
    registration:
      url: ${daemon.base-url}/sign/up
      subject: ${daemon.mail.nick-name} - 注册验证码邮件
    recover:
      url: ${daemon.base-url}/sign/recover
      subject: ${daemon.mail.nick-name} - 密码重置验证码邮件
  sms:
    enable: false
    sign: 【codepasser.com】
    channel: DYXX # DYXX | JTL
    retry-count: 3
    properties:
      # DYXX: 第一信息
      dyxx.api: http://sms.1xinxi.cn/asmx/smsservice.aspx
      dyxx.username: todo@codepasser.com
      dyxx.pwd: todo
      dyxx.type: pt
      dyxx.sign: 【codepasser.com】
      # JTL : 京天利
      jtl.api: http://58.68.247.137:9053/communication/sendSms.ashx
      jtl.cid: 7970
      jtl.pwd: todo
      jtl.productid: todo
      jtl.format: 32
      jtl.sign: 【codepasser.com】
